spring.application.name=hospital-backend

# Aiven MySQL Connection (Fixed URL & SSL)
spring.datasource.url=jdbc:mysql://mysql-201dc059-hospital-managesment-system.e.aivencloud.com:12929/defaultdb?useSSL=true&requireSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_-wt0FGVL9tsRbb1-QOl
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Port
server.port=9090

# Swagger/OpenAPI Path
springdoc.swagger-ui.path=/swagger-ui.html