spring.application.name=hospital-backend

# Connection Details (Directly added to avoid Variable issues)
spring.datasource.url=jdbc:mysql://mysql-201dc059-hospital-managesment-system.e.aivencloud.com:12929/defaultdb?ssl-mode=REQUIRED&useSSL=true&trustServerCertificate=true
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Critical Bean Overriding Fix
spring.main.allow-bean-definition-overriding=true

# Render Port Fix
server.port=${PORT:8080}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
